---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.12.8

platforms:
  - name: trusty64
    driver:
      box: ubuntu/trusty64
      box_url: https://vagrantcloud.com/ubuntu/trusty64/version/1/provider/virtualbox.box
      customize:
        memory: 2048
        cpus: 2

suites:
  - name: default
    run_list:
      - recipe[practicingruby::default]
    attributes:
      practicingruby:
        deploy:
          ssh_keys:
            - some-deploy-key
      postgresql:
        password:
          postgres: practicingruby
