---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.16.4

platforms:
  - name: ubuntu-14.04
    driver:
      box: ubuntu/trusty64
      box_url: https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box
      customize:
        memory: 2048
        cpus: 2

suites:
  - name: default
    run_list:
      - recipe[practicingruby::default]
    attributes:
      practicingruby:
        deploy:
          ssh_keys:
            - some-deploy-key
      postgresql:
        password:
          postgres: practicingruby
