AllCops:
  Includes:
    - Berksfile
    - Gemfile
    - Rakefile
    - Vagrantfile
  Excludes:
    - test/**
    - vendor/**

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
StringLiterals:
  Enabled: false
